/* Generated By:JavaCC: Do not edit this line. EnParserConstants.java */
package de.lathanda.eos.interpreter.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EnParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPORT = 1;
  /** RegularExpression Id. */
  int END_IMPORT = 2;
  /** RegularExpression Id. */
  int PROGRAM = 3;
  /** RegularExpression Id. */
  int END_PROGRAM = 4;
  /** RegularExpression Id. */
  int PROCEDURE = 5;
  /** RegularExpression Id. */
  int END_PROCEDURE = 6;
  /** RegularExpression Id. */
  int METHOD = 7;
  /** RegularExpression Id. */
  int END_METHOD = 8;
  /** RegularExpression Id. */
  int REPEAT = 9;
  /** RegularExpression Id. */
  int TIMES = 10;
  /** RegularExpression Id. */
  int FOREVER = 11;
  /** RegularExpression Id. */
  int UNTIL = 12;
  /** RegularExpression Id. */
  int END_REPEAT = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int THEN = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int END_IF = 17;
  /** RegularExpression Id. */
  int WITH = 18;
  /** RegularExpression Id. */
  int END_WITH = 19;
  /** RegularExpression Id. */
  int CLASS = 20;
  /** RegularExpression Id. */
  int EXTENDS = 21;
  /** RegularExpression Id. */
  int END_CLASS = 22;
  /** RegularExpression Id. */
  int SELF = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int DO = 25;
  /** RegularExpression Id. */
  int END_WHILE = 26;
  /** RegularExpression Id. */
  int TRUE = 27;
  /** RegularExpression Id. */
  int FALSE = 28;
  /** RegularExpression Id. */
  int RESULT = 29;
  /** RegularExpression Id. */
  int BREAKPOINT = 30;
  /** RegularExpression Id. */
  int STOP = 31;
  /** RegularExpression Id. */
  int LPAREN = 32;
  /** RegularExpression Id. */
  int RPAREN = 33;
  /** RegularExpression Id. */
  int SEMICOLON = 34;
  /** RegularExpression Id. */
  int COLON = 35;
  /** RegularExpression Id. */
  int SEPARATOR = 36;
  /** RegularExpression Id. */
  int DOT = 37;
  /** RegularExpression Id. */
  int ASSIGN = 38;
  /** RegularExpression Id. */
  int GT = 39;
  /** RegularExpression Id. */
  int LT = 40;
  /** RegularExpression Id. */
  int EQ = 41;
  /** RegularExpression Id. */
  int LE = 42;
  /** RegularExpression Id. */
  int GE = 43;
  /** RegularExpression Id. */
  int NE = 44;
  /** RegularExpression Id. */
  int OR = 45;
  /** RegularExpression Id. */
  int AND = 46;
  /** RegularExpression Id. */
  int NOT = 47;
  /** RegularExpression Id. */
  int PLUS = 48;
  /** RegularExpression Id. */
  int MINUS = 49;
  /** RegularExpression Id. */
  int MULT = 50;
  /** RegularExpression Id. */
  int DIV = 51;
  /** RegularExpression Id. */
  int POW = 52;
  /** RegularExpression Id. */
  int YELLOW = 53;
  /** RegularExpression Id. */
  int RED = 54;
  /** RegularExpression Id. */
  int GREEN = 55;
  /** RegularExpression Id. */
  int BLUE = 56;
  /** RegularExpression Id. */
  int WHITE = 57;
  /** RegularExpression Id. */
  int BLACK = 58;
  /** RegularExpression Id. */
  int BROWN = 59;
  /** RegularExpression Id. */
  int LIGHT_BLUE = 60;
  /** RegularExpression Id. */
  int LIGHT_GREEN = 61;
  /** RegularExpression Id. */
  int GRAY = 62;
  /** RegularExpression Id. */
  int LIGHT_GRAY = 63;
  /** RegularExpression Id. */
  int DASHED = 64;
  /** RegularExpression Id. */
  int SOLID = 65;
  /** RegularExpression Id. */
  int DOTTED = 66;
  /** RegularExpression Id. */
  int DASHED_DOTTED = 67;
  /** RegularExpression Id. */
  int INVISIBLE = 68;
  /** RegularExpression Id. */
  int FILLED = 69;
  /** RegularExpression Id. */
  int SHADED = 70;
  /** RegularExpression Id. */
  int DARK_SHADED = 71;
  /** RegularExpression Id. */
  int TRANSPARENT = 72;
  /** RegularExpression Id. */
  int CENTER = 73;
  /** RegularExpression Id. */
  int LEFT = 74;
  /** RegularExpression Id. */
  int RIGHT = 75;
  /** RegularExpression Id. */
  int TOP = 76;
  /** RegularExpression Id. */
  int BOTTOM = 77;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 84;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 85;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT2 = 86;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 87;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 88;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 89;
  /** RegularExpression Id. */
  int EXPONENT = 90;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 91;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 92;
  /** RegularExpression Id. */
  int COLOR_LITERAL_RGB = 93;
  /** RegularExpression Id. */
  int COLOR_LITERAL_RGBA = 94;
  /** RegularExpression Id. */
  int IDENTIFIER = 95;
  /** RegularExpression Id. */
  int LETTER = 96;
  /** RegularExpression Id. */
  int DIGIT = 97;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"insert\"",
    "\"*insert\"",
    "\"program\"",
    "\"*program\"",
    "\"procedure\"",
    "\"*procedure\"",
    "\"method\"",
    "\"*method\"",
    "\"repeat\"",
    "\"times\"",
    "\"forever\"",
    "\"until\"",
    "\"*repeat\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"*if\"",
    "\"with\"",
    "\"*with\"",
    "\"class\"",
    "\"extends\"",
    "\"*class\"",
    "\"self\"",
    "\"while\"",
    "\"do\"",
    "\"*while\"",
    "\"true\"",
    "\"false\"",
    "\"result\"",
    "\"breakpoint\"",
    "\"stop\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "\":=\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"yellow\"",
    "\"red\"",
    "\"green\"",
    "\"blue\"",
    "\"white\"",
    "\"black\"",
    "\"brown\"",
    "\"lightblue\"",
    "\"lightgreen\"",
    "\"grey\"",
    "\"lightgrey\"",
    "\"dashed\"",
    "\"solid\"",
    "\"dotted\"",
    "\"dasheddotted\"",
    "\"invisible\"",
    "\"filled\"",
    "\"ruled\"",
    "\"checked\"",
    "\"transparent\"",
    "\"centered\"",
    "\"leftaligned\"",
    "\"rightaligned\"",
    "\"topaligned\"",
    "\"bottomaligned\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\u00a0\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT2>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<COLOR_LITERAL_RGB>",
    "<COLOR_LITERAL_RGBA>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
