/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package de.lathanda.assembler.interpreter.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DATA = 1;
  /** RegularExpression Id. */
  int CODE = 2;
  /** RegularExpression Id. */
  int R0 = 3;
  /** RegularExpression Id. */
  int R1 = 4;
  /** RegularExpression Id. */
  int R2 = 5;
  /** RegularExpression Id. */
  int R3 = 6;
  /** RegularExpression Id. */
  int R4 = 7;
  /** RegularExpression Id. */
  int R5 = 8;
  /** RegularExpression Id. */
  int R6 = 9;
  /** RegularExpression Id. */
  int R7 = 10;
  /** RegularExpression Id. */
  int R8 = 11;
  /** RegularExpression Id. */
  int R9 = 12;
  /** RegularExpression Id. */
  int R10 = 13;
  /** RegularExpression Id. */
  int R11 = 14;
  /** RegularExpression Id. */
  int R12 = 15;
  /** RegularExpression Id. */
  int R13 = 16;
  /** RegularExpression Id. */
  int R14 = 17;
  /** RegularExpression Id. */
  int R15 = 18;
  /** RegularExpression Id. */
  int A = 19;
  /** RegularExpression Id. */
  int B = 20;
  /** RegularExpression Id. */
  int LPAREN = 21;
  /** RegularExpression Id. */
  int RPAREN = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int SEPARATOR = 24;
  /** RegularExpression Id. */
  int INC = 25;
  /** RegularExpression Id. */
  int DEC = 26;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 32;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 33;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT2 = 34;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 35;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 36;
  /** RegularExpression Id. */
  int HEXADECIMAL_LITERAL = 37;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 38;
  /** RegularExpression Id. */
  int EXPONENT = 39;
  /** RegularExpression Id. */
  int STRING_LITERAL = 40;
  /** RegularExpression Id. */
  int IDENTIFIER = 41;
  /** RegularExpression Id. */
  int LETTER = 42;
  /** RegularExpression Id. */
  int DIGIT = 43;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"data\"",
    "\"code\"",
    "\"r0\"",
    "\"r1\"",
    "\"r2\"",
    "\"r3\"",
    "\"r4\"",
    "\"r5\"",
    "\"r6\"",
    "\"r7\"",
    "\"r8\"",
    "\"r9\"",
    "\"r10\"",
    "\"r11\"",
    "\"r12\"",
    "\"r13\"",
    "\"r14\"",
    "\"r15\"",
    "\"a\"",
    "\"b\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT2>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEXADECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
